### ISSUE TITLE
Forms not restricted to an entity

### ISSUE THREAD

**Issue by blacksushi42** [pluginsGLPI/formcreator#1030]
Hello,

I wanted to report than when we have a form restricted in an entity, we can load it and validate it in another entity. We have simply change entity with the selector.

"Destination entity" set up to "current active entity" make than tickets are not really create where we wanted.

I'm on glpi 9.3 and formcreator 2.6.3

Best regard

**Comment by btry** [comment]
Hi

THis needs clarification. The plugin works with several objects.

The form is the thing designed by an administrator. Consider  this is the empty form you get when you want to fill a request.

When fill a form with your answers and save it, you no longer have a form but a set of answers. 

The destination entity you find in the target ticket is the entity where will be saved the generated ticket.

Also, a form has a recursive bit. This means that the form is accessible from an entity which is direcet or indirect child of the entity where is located the form.

To review your case properly, I need you describe your entities hierarchy and locate in it : 
- the form, 
- the user who validates the form,
- the ticket  generated by the form

**Comment by btry** [comment]
After conf call,

the issue is a missing check when a user is filling a form.

### To reproduce

- Create a form in the entity Root > A
- Login as a user in the entoty Root > A and access the form to fill it
- connected as the same user, switch to the entoty Root > B

### expected

the access to the form is denied

### observed

the user has access to the form and can fill it.

**Comment by btry** [comment]
Reopened due to several feedbacks.

see #1055 for a enhancement
