### ISSUE TITLE
Fatal error in Form answers

### ISSUE THREAD

**Issue by neogorn** [pluginsGLPI/formcreator#1067]
Falta error to access Form answers after upgrade glpi version 9.2.3 to 9.3.0.

**Debug mode :** Fatal error: Call to undefined method PluginFormcreatorForm_Answer::getSearchOptions() in /var/www/html/glpi/plugins/formcreator/inc/form_answer.class.php on line 367

![error](https://user-images.githubusercontent.com/42190708/43806694-6a216d02-9a7b-11e8-9ff8-6ded6c3c3345.JPG)

Tks.

**Comment by btry** [comment]
Hi

Unfortunately formcreator is not compatible with GLPI 9.3 due to changes in api of GLPI.

Issues were detected lately, which explains that the version 2.6.3 is advertised compatible.

 I'm fixing it in the incoming version 2.6.4. If you want to test it (branch develop at time of writing) I would appreciate your feedback.

**Comment by neogorn** [comment]
Ok, I will tray.

Tks for replay.

**Comment by neogorn** [comment]
Hello.

The problem has been fixed in version 2.6.4

Tks.

**Comment by btry** [comment]
Thanks, I close the issue
