### ISSUE TITLE
Erro ao inserir resposta do Formulário no campo descrição do Chamado Associado.

### ISSUE THREAD

**Issue by rafaelrdm** [pluginsGLPI/formcreator#1334]
**Describe the bug**
Elaborei algumas questões ao montar um formulario.
Configurei o formulario associando ele para registrar um chamado no GLPI.
Mas as questões elaboradas e não respondidas pelo usuário, quando já inseridas pelo Sistema no Campo Descrição do Chamado, ficam em branco.
Ex. Selecione a UF: (Sistema exibe lista de Estados disponiveis)
Ao selecionar o Estado, sistema exibe a proxima questão que estava oculta, listando os Municipios do Estado selecionado.

Quando envio para registrar o chamado, sistema exibe as respostas das questões selecionadas, mas tambem deixa um espaço em branco para questões não respondidas no formulário.

**To Reproduce**
1. Cadastre um Questão no Formulário 
    - Título: UF de Residência
    - Tipo: Selecionar
    - Campo Valores(Um por linha): Cadastre umas 5 opções
2. Cadastre um Questão no Formulário (Repita pela mesma quantidade de UF cadastrada no item 1
    - Título: Município de Residência
    - Tipo: Selecionar
    - Campo Valores(Um por linha): Cadastre umas 5 opções
    - Campo Exibir Campo: "Escolha Escondido a menos que" = UF de Residência = "Algumas das opções cadastrada no passo 1
3. Após criação do Formulário.
4. Escolha a opção Destino e adicione algum destino.
    - Campo Descrição: informe a lista de tags disponíveis logo abaixo na tela"
        Ex. ##question_01## | ##answer_01##
             ##question_02## | ##answer_02##
             ##question_03## | ##answer_03##
             ##question_04## | ##answer_04##
5. Após criar e configurar o formulário simule o envio do formulário, selecionando um Estado e Município. 

6. Acesso chamado que foi gerado com o envio do formulario e visualize o campo Descrição do Chamado. Irá verificar que o campo foi preenchido com as informações do formulário, mas exibindo campos vazios, que são referentes as questões não respondidas no formulário.

**Expected behavior**
Que o sistema informasse no campo descrição do chamado apenas as questões respondidas e ocultasse as questões que tenha alguma condição para sua exibição.

**Screenshots**
![image](https://user-images.githubusercontent.com/48140189/53672039-4b9e5600-3c57-11e9-8bd8-522466fff38c.png)

![image](https://user-images.githubusercontent.com/48140189/53671979-109c2280-3c57-11e9-8cdf-74d171d37ced.png)

**Comment by btry** [comment]
Hi

Please, write in english: I cannot read spanish. I used a translator and if I understand well, you reported white lines in the generated ticket.

This is complex to fix because with rich text mode and a custom template (when not using the tag ##FULLFORM##) the useless lines will be not predictable and hard to detect. I think that the plugin needs a better templating engine, like email notifications in GLPI.

**Comment by rafaelrdm** [comment]
Would there be any alternative to configure the form so that in the description field only displays the answers informed in the form?

**Comment by btry** [comment]
If you use the  ##FULLFORM## tag instead of your own ticket description, then the plugin is able to avoid empty lines.

Here is the involved code: https://github.com/pluginsGLPI/formcreator/blob/develop/inc/formanswer.class.php#L1222

##FULLFORM## generates a default description template for the target. If you don"'t have specific needs to render  the target ticket, this may be your solution.

**Comment by btry** [comment]
Hi

Having no feedback, I close this ticket.
