### ISSUE TITLE
[GLPI-9.4.1.1] Error is Multiple primary key defined

### ISSUE THREAD

**Issue by gloomy-master** [pluginsGLPI/formcreator#1376]
Good afternoon, developers.
I am trying to install a plugin 2.8.0 in GLPI 9.4.1.1

When trying to turn on, I get the following error:
> Change of the database layout - glpi_plugin_formcreator_forms_profiles (1 second)
2.8.0 multiple alter in glpi_plugin_formcreator_forms_profiles - Error during the database query: ALTER TABLE `glpi_plugin_formcreator_forms_profiles` CHANGE `plugin_formcreator_profiles_id` `profiles_id` INT(11) NOT NULL DEFAULT '0' , ADD `id` INT(11) NOT NULL AUTO_INCREMENT , ADD PRIMARY KEY `id` (`id`) , ADD UNIQUE KEY `unicity` (`plugin_formcreator_forms_id`, `profiles_id`) , ADD `uuid` VARCHAR(255) COLLATE utf8_unicode_ci DEFAULT NULL - Error is Multiple primary key defined 

How to solve a proble

**Comment by btry** [comment]
Hi

Is this an install or an uprgade ? If this is an upgrade, which is the older version of the plugin you used ?

**Comment by gloomy-master** [comment]
I used in a very old version 0.85 earlier and have now updated the GLPI itself and am trying to connect the plugin itself

**Comment by btry** [comment]
Hi

I'm not sure about the history of your GLPI. Be aware that very old versions of the plugin did not remove all its tables on uninstallation. This fools the latests versions if you re install it. Instead of running a clean install the plugin will try to upgrade. If you expect that the plugin runs a clean install, then check in the DB if you find tables beginning with **glpi_plugin_formcreator_**. If yes, you must drop all of them. Next you can try to install the plugin.

If you are NOT expecting a fresh install, then try instead to upgrade to version 2.4.0 then 2.5.0 then the latest. This will probably require that you upgrade your GLPI to intermediate versions to ensure compatibility of GLPI with the plugin.

**Comment by gloomy-master** [comment]
Yes, thanks for the hint, I deleted the problem tables and reinstalled the plugin again.

**Comment by btry** [comment]
Hi

Fine, but you did not told if the plugin installed successfully (then I don't know if I can close :) )

**Comment by gloomy-master** [comment]
Thanks, you can close
