### ISSUE TITLE
Add id of ticket in selection list

### ISSUE THREAD

**Issue by mab18** [pluginsGLPI/formcreator#1669]
Hi,
As in GLPI, when selecting an identical ticket associated, is it possible to add the ticket ID in list of tickets ? This should permit to select by the ID, the description is not always relevant.

**Describe the solution you'd like**
Just after the description of the ticket, add the ticket ID.  As in "GLPI" ticket form.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://user-images.githubusercontent.com/55535560/74033591-cb2fbb80-49b6-11ea-9974-0b890d06ddd4.png)
Selecting the right ticket is not easy without ID. In GLPI, it's ok if we know the ID.
![image](https://user-images.githubusercontent.com/55535560/74033663-f4504c00-49b6-11ea-9928-362d5bb2ab2a.png)
In formcreator, linking to a ticket is impossible in the same case.

EDIT : I use ID in my dev profile, they are in brackets, users don't.
EDIT : example above is from /glpi/front/ticket.form.php in link to another ticket

**Comment by btry** [comment]
Hi

I'm checking with the version 2.9.2 in dev. It seems ok for me. Could you validate with a testing environment  and this version ?

**Comment by mab18** [comment]
Does I need to install all the dev environment or just a file is needed ?

**Comment by btry** [comment]
Hi

 I don't remember easily the date, and the lines changed for the fix. The fix which should solve the issue is probably several months old now.
I give you a build of the current revision. This should help you validate the status of the  future 2.9.2 version. Keep in mind it is not ready for production.


[glpi-formcreator-2.9.2-dev.zip](https://github.com/pluginsGLPI/formcreator/files/4369853/glpi-formcreator-2.9.2-dev.zip)

**Comment by mab18** [comment]
Hi,
Sorry, but it's not in this release :
![image](https://user-images.githubusercontent.com/55535560/77417237-66dd8580-6dc5-11ea-9709-47c88e1bb248.png)

**Comment by btry** [comment]
Hi 

This commit should solve the issue : 293c3167

**Comment by btry** [comment]
This fix will  be included **after** the release 2.10.3
