### ISSUE TITLE
Footer locked in middle of forms when using vertical split view

### ISSUE THREAD

**Issue by jnfohr** [pluginsGLPI/formcreator#1676]
Hi,

When using a vertical split view in GLPI, the footer in a form is locked at the botom of the visible part of the page once this one has more than ~ 1200 px horizontal resolution.
It doesn't happen if the window is less wide

Scrolling down leaves the footer in the middle of the form

![image](https://user-images.githubusercontent.com/23486281/74221278-0c271900-4cb2-11ea-8ea4-3c767fd2f949.png)

Tested on firefox and chromium, same result

**Comment by btry** [comment]
Hi

With which versions of GLPI and Formcreator ? Also, if there is a textarea in the form, please check if this still happens wqith a form without such type of question.

**Comment by jnfohr** [comment]
GLPI 9.4.5
Formcreator 2.9.1

Indeed, ther is a textarea in the form, and once removed, the issue disappears

**Comment by btry** [comment]
Ok, then try this patch: https://github.com/pluginsGLPI/formcreator/commit/4e5ed459d6ba95a08c9306828024a27fd5bed7d3 and feedback

**Comment by jnfohr** [comment]
Thanks, the patch fixes the issue.

Regards,

**Comment by gal30** [comment]
Hi,

We have the same issue and we tried to install the patch (same versions too)
Infortunaly, this is not working for us.


- When enable_fileupload = false : The textarea isn't displayed. The bug is resolved.
- When enable_fileupload = true : The textarea is displayed. The bug isn't resolved. 
In both cases : the div fileupload_info is added.

FYI : The textarea is showed only when à field is not empty. 

Regards

**Comment by btry** [comment]
Hi

You may add the patch for GLPI which solves the root cause of the issue : https://github.com/glpi-project/glpi/pull/6811

the file area shall not display if you set enable_fileupload = false. Maybe the patch is not properly applied ?

**Comment by gal30** [comment]
Hi,

With both patchs is resolved

Thx :)

**Comment by btry** [comment]
thanks for the fedback
