### ISSUE TITLE
Space between elements

### ISSUE THREAD

**Issue by andersonmarcondes** [pluginsGLPI/formcreator#1704]
At GLPI 9.4.5 and Forms versions 2.9 and 2.10.0 (IIS at Windows Server 2019) there is an excessive space between elements when a form is created.
--
![form image](https://user-images.githubusercontent.com/27715428/76647836-4d724900-653c-11ea-8b98-80f49ad4c1f3.png)

**Comment by btry** [comment]
Hi
This bug was found a few days ago. Try to update your version to the latest revision : support/2.9.0 for 2.9.x and support/2.10.0 for 2.10.x

Remember that versions 2.10.x are not released yet then not ready for production, and I'm focusing on 2.9.2 for now.

The commit you need should be : https://github.com/pluginsGLPI/formcreator/commit/afa2ea386b297858f8d78ad9f5fb41f4a691189e

**Comment by btry** [comment]
Hi 

Do you still reproduce with the latest versions od 2.9 and 2.10 ?

**Comment by btry** [comment]
Hi

This should be solved in 2.9.2
