### ISSUE TITLE
 Full name in form category

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#1734]
Hello

Not sure if this behavior is a bug. In previous versions, the "full name" of the form category was not displayed.

From 2.9 it is presented, and it makes the visualization not look good.

Is there any way to disable the full name in version 2.9.1?

![image](https://user-images.githubusercontent.com/35368369/80000920-26d8f380-8494-11ea-9e0b-7266fe392742.png)

**Comment by phamorais** [comment]
Hi @btry 

I will update to v292 tomorrow. I saw that the correction is not in the changelog. Should it be fixed only in v10?

**Comment by phamorais** [comment]
@btry 

Update the test environment to v2.9.2 and the problem has been fixed

![cat](https://user-images.githubusercontent.com/35368369/82507127-d32fe900-9ad7-11ea-9ce2-1db18c94d0c6.gif)

**Comment by btry** [comment]
Hi

The fox is not in the changelog because I added the fix by hands in the archive of the release 2.9.2. However the tag was created a few hours before.

Actually I should not do this, but I wanted to avoid annoyance to users. The archive is a few commits ahead the 2.9.2 tag, making it slightly different.

The fix is in the next releases, and will be in the changelog.

**Comment by btry** [comment]
As the bug is solved, I close this issue.
