### ISSUE TITLE
Cannot add more question

### ISSUE THREAD

**Issue by bacus99** [pluginsGLPI/formcreator#1865]
GLPI 9.5 and Formcreator 2.10

I just upgrade and forms works well, but I can't

- Add a new question
- Add a target

Clicking on +add a target say "javascript:plugin_formcreator_addSection(1, '5f51054be845a6b2f1affed488ac7d712d86f6cce8e621e4e401f049b9a46ad5');" but nothing happen

Thank you

**Comment by bacus99** [comment]
javascript:plugin_formcreator_addTarget(1, '52f94e9bbbc6d97c2b973db65ac2c7dd5783daf570dc462fe71db85ef50ce02b');

Also

**Comment by btry** [comment]
Hi


I believe that you installed the plugin from the marketplace. Such installation break the plugin; i'm currently fixing this for the next release.

You can workaround by installing the plugin with the legacy method.

**Comment by btry** [comment]
Hi

I created 3 patchs to fix several problems with the marketplace. See https://github.com/pluginsGLPI/formcreator/issues/1856

**Comment by bacus99** [comment]
I uininstall, reinstall from plugins.  Error is related to this link

![image](https://user-images.githubusercontent.com/11425241/87333276-e7f29100-c50a-11ea-9de7-92ed5870bb88.png)

**Comment by btry** [comment]
This link calls a JS functon which is not available bacause the JS code was lon loaded in the browser. 

The patches should fix it. However, if you try to reinstall from the marketplace, the version of Formcreator will not include the fixes because they are not yet part of the latest release.

Depending on your skills you may 
- apply the patches manually with the **patch** tool
- install the plugin with git in the glpi/marketplace directory
- instal an archive I may prepare for you, in glpi/marketplace 

Let me know which solution you prefer.

**Comment by bacus99** [comment]
I know GLPI well, but never heard about a patch tool :)  Usually, I dl the files and overwrite them

**Comment by btry** [comment]
You should not overwrite a file of the plugin with an other because you may break something else if the file contains an other fix which requires changes elsewhere.

Here is the man page about patch

https://linux.die.net/man/1/patch

Basic usage, assuming you're in the directory of the plugin

Will emulate application of the patch
patch -p1 --dry-run < /path/to/patch.patch

Will actually apply the patch
patch -p1 < /path/to/patch.patch

Will revert the patch, when it is already applied
patch -p1 --reverse < /path/to/patch.patch

**Comment by bacus99** [comment]
Works with 2.10.1, good job

**Comment by btry** [comment]
Great ! 

Thank you for your feedback.
