### ISSUE TITLE
Tickets counter 0

### ISSUE THREAD

**Issue by Alextizgz** [pluginsGLPI/formcreator#1996]
Hi, I have this issue.:
The user fills in the form, the ticket is created, but the top counter does not change
![001](https://user-images.githubusercontent.com/73636091/97541442-74936300-19c5-11eb-9025-47d3aafee532.jpg)

The, the administrator closes the ticket, but the status of the ticket on the main screen does not change, it remains as new
![002](https://user-images.githubusercontent.com/73636091/97541994-537f4200-19c6-11eb-880c-ddb8f34ad895.jpg)

![003](https://user-images.githubusercontent.com/73636091/97542012-57ab5f80-19c6-11eb-9284-393ec56fccdc.jpg)

Is a fresh installation of ubuntu, glpi and pluggin, the users are default users
No sql errors and no php errors

**Comment by btry** [comment]
Hi

Which version of GLPI and Formcreator ?

Usually, this issue is related to a SQL error and in the recent versions of the plugin an SQL error shows **N/A** instead of **0**. I guess you're not using a version 2.10.x of Formcreator, which is the latest version.

**Comment by Alextizgz** [comment]
GLPI 9.5.2 and Formcreator 2.10.3

**Comment by btry** [comment]
Ok, then you are impacted by a regression in the version 2.10.3. Apply the following patch

https://github.com/pluginsGLPI/formcreator/pull/1983

then try to create a new ticket via Formcreator. It should be OK.

To recover the missing ticket in the counter, please erase all rows in the table  **glpi_plugin_formcreator_issues**, then manually run from GLPI the automatic action "SyncIssues". IT will rebuild the content of the table and your counter should show the good values.

I plan to release a new version in november, because of this too much annoying bug.

**Comment by Alextizgz** [comment]
Solved!!!

Thanks!
