### ISSUE TITLE
Links between models

### ISSUE THREAD

**Issue by rodrigojh** [pluginsGLPI/formcreator#2035]
**Describe the bug**
Hi,
We installed the FormCreator plugin and it is working correctly, but we are facing some problems.
In the Form maintenance, in the "destination" field, the editing tools do not appear so that you can customize the way the ticket is delivered to the IT team.

Another point, which is more of a doubt, is whether the formcreator has a direct link to the fields of the standard form, so that the internal rules work correctly and that it doesn't just come as a description.
If this is possible, where do I find documentation on this?
![formcreator1](https://user-images.githubusercontent.com/41808416/100897686-b6209d80-349e-11eb-8080-32946902f604.jpg)
![formcreator2](https://user-images.githubusercontent.com/41808416/100897720-c173c900-349e-11eb-9099-53ca2e2a0bc5.jpg)

**Comment by btry** [comment]
Hi

>  We installed the FormCreator plugin and it is working correctly, but we are facing some problems.
In the Form maintenance, in the "destination" field, the editing tools do not appear so that you can customize the way the ticket is delivered to the IT team.

Do you have javascript errors in the browser ? I also notice that the ticket does not show its editing tools and Formcreator cannot and does not control if the textarea is a simple text input or a rich text iinput. GLPI dropped a few years ago the simple text mode. Check also if you have JS errors in the ticket view.

> Another point, which is more of a doubt, is whether the formcreator has a direct link to the fields of the standard form, so that the internal rules work correctly and that it doesn't just come as a description.


Formcreator does not create tickets directly to the database. It sends its data to GLPI. business rules should be applied as usual. However the HTML genertaed by Formcreator in description of a ticket michg be overcomplicated or non standard compliant (<p> nested in a <p> is an example). Some business rules may fail with Formcreator and you may need to enhance them to fix this problem. Users who reported this case had to read the HTML in the database directly to update their business rule as the HTML generated by the plugin is hard to predict.

**Comment by btry** [comment]
Hi

Having no feedback, I close this issue.
