### ISSUE TITLE
Error when cloning forms V2.10.4

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/formcreator#2060]
**Describe the bug**
When cloning a form, it is cloned missing several questions and displays the message "UUID or ID is mandatory for Question regular expression"

![erro duplicate](https://user-images.githubusercontent.com/35368369/103013726-5f960480-451c-11eb-80ad-20ba5d9588b9.gif)

Error log

![image](https://user-images.githubusercontent.com/35368369/103013970-cb786d00-451c-11eb-8ffc-b450b0f3f0e6.png)

**Expected behavior**
Duplicate form successfully

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - GLPI 9.5.3

**Comment by btry** [comment]
Hi 


If your form was created with an older version of Formcreator, you may have an inconsistency in the database caused by an old bug. It is often possible to fix the inconsistency by editing the question causing the error, then saving it without any change.

The question causing your error is a question using a regular expression parameter like a text question. Try on all of these questions the above fix, then try again.

**Comment by phamorais** [comment]
Hello @btry 
The only issue that I have something that fits these conditions is the character range

![image](https://user-images.githubusercontent.com/35368369/103296303-9f556400-49d4-11eb-80be-687fecbc9a20.png)

However, even after removing the problem continues :(

![formcreator1](https://user-images.githubusercontent.com/35368369/103296895-dc6e2600-49d5-11eb-8404-b58398c66f8a.gif)

**Comment by btry** [comment]
Hi

I see you have 4 questions of type text. Edit all of them, and save them. You don't need to delete and restore anything. Just click the save button. If the regular expression field is empty, you still need to update the question. Once done, the form should update properly.

**Comment by btry** [comment]
Hi @phamorais : did you try to edit all text question as described above ? Did it work ?

**Comment by btry** [comment]
Hi

HAving no feedback, I assume the problem is solved. I close.
