### ISSUE TITLE
Error creating tables : You have an error in your SQL syntax

### ISSUE THREAD

**Issue by empereira** [pluginsGLPI/formcreator#2067]
**Describe the bug**
Not too much to describe, except that glpi installation are in a docker container. The GLPI version is 9.4.6 and I try to install the formcreater plugin, but always occurs the error:

```
Error creating tables : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS `glpi_plugin_formcreator_categories` ( `id` int(11)' at line 14

Giving up
```

**To Reproduce**
1. Download the latest version into plugins folder
2. Extract .bz2 file
3. Change permissions of plugin folder
4. Go to GLPI web, click on Settings > Plugins > Install formcreator

**Expected behavior**
I expect the correct installation of formcreator plugin

**Desktop (please complete the following information):**
 - OS: ubuntu 18
 - Browser: chrome, firefox
 - Version: latest

**Comment by btry** [comment]
Hi

The SQL query is incomplete, and of course, it is syntaxically incorrect. I guess the request is not executed from PHP code because an error from PHP parser would occur first. Then I would check if the file **install/mysql/plugin_formcreator_empty.sql** is the same size as in the same file in the archive.

If it is incomplete I would recommend you to remove and re-copy the plugin files in your docker container. You probably had a failure while copying the plugin in the container.

**Comment by empereira** [comment]
hello @btry, thanks for the answer!!!

The files are the same!!!

I believe it was some problem with my db. Maybe a wrong old installation. idk

I had to create a temporary db and tables, copy to production db, restart the containers and then drop the tables. After that, the installation worked correctly.
