### ISSUE TITLE
[2.11.1] Regex in condition don't work for dropdown

### ISSUE THREAD

**Issue by usrqmor** [pluginsGLPI/formcreator#2130]
Bug Description : 
When using a regex condition to hide or show a question on dropdown, it doesn't work.

To reproduce :
	1. Create a question A with a dropdown as a result (in my case ticket categories)
	2. Create a second question B : choose "Hide unless" or "Show unless" with "Regular expressions matches" (screenshot regex on_dropdown)
	3. Set your regular expression
	4. Choose in question A categories which matches the regex
	5. The question B doesn't show or isn't hidden  (screenshot result_fill)

Screenshot :
![regex_ondropdown](https://user-images.githubusercontent.com/17316903/107777967-cc22c800-6d43-11eb-96a8-553671024725.jpg)
![result_empty](https://user-images.githubusercontent.com/17316903/107777974-cd53f500-6d43-11eb-8969-561f385d4acc.jpg)
![result_fill](https://user-images.githubusercontent.com/17316903/107777980-cdec8b80-6d43-11eb-99bf-13a51d9685a6.jpg)
![regex_ontext](https://user-images.githubusercontent.com/17316903/107777983-cf1db880-6d43-11eb-98d5-2407cc78ed32.jpg)

Expected Behavior
When choosing a categories ticket that matches the regex, question B must be visible.
It works for text 

Deskop
OS : Windows 10 64bits
Browser : Firefox 
Version : 85.0.2

Additional context :
I've join a screenshot when the regex worked (screenchot regex_ontext)
I try my regex on different website to be sure that I dont write a bad regex but it didn't seem the case.

Thanks in advance for your help.

Regards

**Comment by btry** [comment]
Hi

The new feature for regex comparison does not support dropdowns. Internally, Formcreator refuses the comaprison because this is not implemented.

You will find aboce a fix which solves that. Please note that the regex is compared against the **short** name of the item selected in the dropdown.

I'm waiting for your feedback.

**Comment by usrqmor** [comment]
Hi btry,

Thank you for your reply. 
I apply your fix and on the 20 files to modify, I had to modify only one (dropdownfield.class.php) . The other were already good. 
The fix works for the short name of the selected item like you said.

Since, it's a feature, I'll wait for the next fix that will allow to compare the entire name of a selected item.

Thanks again for the help.

**Comment by btry** [comment]
Hi

> I apply your fix and on the 20 files to modify, I had to modify only one (dropdownfield.class.php) . The other were already good.

This is because I did a wrong manipulation. The fix reverts something else I worked before. You applied correctly the patch anyway, and I updated it to contain only the useful part.

I cleaned up the patch and added a way to handle complte name. This is more consistent with others comparisons. Please try this version and feedback.

**Comment by usrqmor** [comment]
I apply the fix and it works well !
The regex works on the entire name of selected item on dropdown.

Thanks a lot for your help !
