### ISSUE TITLE
GLPI format ID 

### ISSUE THREAD

**Issue by jvergacas** [pluginsGLPI/formcreator#2150]
Hi

When a user searches for their tickets, the ID is presented with the suffix "t_":
![image](https://user-images.githubusercontent.com/43650152/109043208-d8961180-76af-11eb-8f6c-cb6c44844c4b.png)

My suggestion is to show the ID as the ticket is shown in the other profiles:
![image](https://user-images.githubusercontent.com/43650152/109043454-1e52da00-76b0-11eb-8ce7-e7139048d79d.png)

For this I replaced in the issue.class.php file, in lines 417 and 424, the values of the fields 'display_id' for 'original_id'
![image](https://user-images.githubusercontent.com/43650152/109044396-1e9fa500-76b1-11eb-9a39-3f30821a9d28.png)

I think it looks better this way.

Thanks

**Comment by btry** [comment]
Hi

You should not do this. The search option numbered 2 shall be unique. This is usually an ID column in any table. The table glpi_plugin_formcreator_issues is special because it contains a mix of data coming from 2 different tables. Its column display_id contains prefixes t_ and f_ to ensure unicity. It is possible to collect a row numbered 42 from a ticket and a row numbered 42 from a formanswer. In such case the prefix helps to know to which itemtype the row refers. 

This may not be useful for a self-service user, but for technicians or admins who needs to debug something in Formcreator, this data is valuable. Also, I cannot say that your change won't have bad side effect when a search is done on the issues table (counters and lists of issues in service catalog).

**Comment by jvergacas** [comment]
Hi @btry 

How would I go about showing a self-service user the original_id instead of the display_id? 

Thanks

**Comment by btry** [comment]
I think that the best would be some development to use display preferences feature of GLPI.

**Comment by killerh777** [comment]
Hi, I have the same problem, I noticed that the table used by the formcreator is different from the standard table used by GLPI, so the calls opened by the form do not appear on the service dashboard.

![image](https://user-images.githubusercontent.com/80044964/109988862-b3745500-7ce6-11eb-98c4-fbdf866e0feb.png)

the 5 tickets(Chamados) identified in the counter above were opened in the original layout without the forms.
![image](https://user-images.githubusercontent.com/80044964/109989016-d868c800-7ce6-11eb-999c-1c8030a4c7b4.png)

Table formcreator
![image](https://user-images.githubusercontent.com/80044964/109989148-fdf5d180-7ce6-11eb-9574-cc6cbd752d56.png)

Table GLPI
![image](https://user-images.githubusercontent.com/80044964/109989451-444b3080-7ce7-11eb-9ac8-55c72811b3b2.png)

**Comment by btry** [comment]
Hi
 @killerh777 

First we need to agree with terms. Usually, a call is a ticket, stored in **glpi_tickets**.  Formcreator handles assistance requests stored in the  table **glpi_plugin_formcreator_issues**, manages form answers in  **glpi_plugin_formcreator_formanswers**, and each answer to a single question for a given form is stored in **glpi_plugin_formcreator_answers**.

In the service catalog you don"'t see calls but an assistance requests. Assistance requests are the mirror of 2 types of objects : calls (or tickets) and form answers. You may wonder why this design. Formcreator can generate no, one or several tickets from a form answer. This is configured by the admin who designs a form, tab **Targets**. 

Depending on how many tickets are generates whe filling a form answer, the assistance request mirrors a ticket or the form answer itself.
If there is one and only one ticket, then the assistance reqiest mirrors the ticket.
In all other cases the assistance request mirrors the form answer.

You may recognize the mirrored object by reading the prefix of the ID in the assistance requests list. f_ means form answer, t_ means ticket. This is saved in the column display_id. You can also see that in the table by reading the column **original_itemtype**

I also see 2 rows with an empty display_id. This is not normal. Maybe you manipulated the table manually. I Don't remember of a bug report pointing this behavior.

Because of this design it is a bad idea to do the change submitted by @jvergacas : this will lead to ID conflict between 2 types of objects and I cannot predict the issues it will cause when the search engine of GLPI will use the assistance requests.

I hope that those explanations will help you to understand how Formcreator works

**Comment by killerh777** [comment]
@btry Thanks for the help, it worked, as soon as I added the target the requisitions started to appear.

![image](https://user-images.githubusercontent.com/80044964/110026445-66f13f80-7d0f-11eb-8794-e67fc5d3750b.png)


About tickets that are unnumbered, it was a test I did doing exactly what you said would not work.

**Comment by btry** [comment]
Hi

@jvergacas @killerh777  can we close this issue ?

**Comment by jvergacas** [comment]
Hi @btry 

Yes, we can close, but in my opinion, as this screen is accessed by users, it would be better to show information that the user understands and can pass correctly.

Thanks.

**Comment by btry** [comment]
Hi

Maybe should we show the column **sub_itemtype** and the **original ID** ? I'm afraid this will make a bit more confusing for end users.

**Comment by btry** [comment]
Hi

@killerh777 : Formcreator implements validation process. When a form under validation is filled by a requester, no target is generated, until the answers are accepted. Before this event, answers are saved in database, and the requester may need to view them. 

it is also possible to generated several target tickets.

Because of that, Formcreator shows either the generated ticket (when there is one and only one) or the "raw" answers in other cases.

**Comment by jvergacas** [comment]
Thanks
