### ISSUE TITLE
Set a Form as default

### ISSUE THREAD

**Issue by ArriMa** [pluginsGLPI/formcreator#2299]
To simplify ticket opening an idea wold be to set a Form as default (maybe a different setting from each entity).
And hide the list of possibile form

**Comment by btry** [comment]
Hi

You can already set a form as default. Default forms are displayed when no form matches the criteria of the user (form category + keywords).

**Comment by ArriMa** [comment]
Ok, what I mean is that if I mark a form as default (or another way if default concept is "show anyway" also if search field is empty), I would like that when i select "Seek assistance" that form are loaded immediatly without show all available forms.
This is useful if I have one dedicate forms instead use the standard GLPI ticket creation.

**Comment by btry** [comment]
Hi

you may change the code matching the left panel's menu. Where is defined the URL to the list of forms, set the URL to your the form you want to show.

**Comment by ThibautStark** [comment]
The lines to change are 7104 and 7259 in html.class.php. You will have to put a criteria on the html results to discriminate the "Add ticket" option from the others.

**Comment by ArriMa** [comment]
Ok, thanks.
Information only, do you think this feature will be implemented or I have to proceed with this workaround?

Maybe this feature could be managed under:
Entity -> Forms -> Helpdesk Mode and insert here an option such as "Load specific form" and once selected another listbox with all existing forms that could be selected?

Thank you

**Comment by btry** [comment]
Hi

This feature is not in the roadmap for now. I'm not sure i will merge it : the purpose of the  plugin is to provide access to several forms, depending on the need. A single form (whici is probably absolutely not specialized to fit a type of request) is satisfied by the self service of GLPI. 

Also, modifying html.class.php is not a solution because this file belongs to GLPI. A good implementation requires something in the plugin only.

**Comment by ArriMa** [comment]
Ok, clear. Thank you
