### ISSUE TITLE
Correct FormCreator name in plugins list

### ISSUE THREAD

**Issue by nototbol** [pluginsGLPI/formcreator#2307]
In plugin list (Administration > Plug-ins) has FormCreator bad name. Correct is FormCreator, but in list is with space (Form Creator).
Please, correct it.

![obrázok](https://user-images.githubusercontent.com/63390579/126127583-ed422a60-c89d-4c31-b87d-ebc54413e884.png)

**Comment by btry** [comment]
Hi

Why is this an issue ?

**Comment by nototbol** [comment]
Hi, beacause official name is FormCreator, not Form Creator. Try serach information on the web for "Form Creator" and then for "FormCreator". For new user is this issue.

**Comment by nototbol** [comment]
Same issue in Dropdowns page
![obrázok](https://user-images.githubusercontent.com/63390579/127277373-4dbfa001-936f-4f8b-ab82-9a73aea01e9d.png)

**Comment by btry** [comment]
Hi

As an example, the plugin Generic object, usually named this way, has an other name in the UI of GLPI. The string you want to change is translated into Form Creator because this is more a term for humans, and Formcreator is more technical name  (unicity and key to find the plugin's files).

![image](https://user-images.githubusercontent.com/14139801/127514810-6ff8efce-68e4-4a54-b320-ff4de5f95720.png)

On a search engine, you will find a lot of things unrelated to the plugin by searching for "form creator". adding the word GLPI give far better results, and it is necessary because the plugins does something which exists in many (web) applications and is also 2 generic words found in a dictionnary (making their use on a lot of unrelated topics).

![image](https://user-images.githubusercontent.com/14139801/127515885-decd6333-8703-4b8b-9116-e0b7b8fb7630.png)

**Comment by btry** [comment]
Hi

I think we can close this ticket. The marketplace and the glpi plugins website is the best place to find additional features for GLPI.

https://plugins.glpi-project.org/
