### ISSUE TITLE
Request type on Target is not respected. 

### ISSUE THREAD

**Issue by luizfss** [pluginsGLPI/formcreator#2387]
**Describe the bug**
In **Request Type** field (target), when **Specific type** is informed, the ticket does not respect the type informed, he brings for the default type in the entity's record. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16945922/131738557-0a5dc5ce-fc50-4cc5-b11f-379627100454.png)

![image](https://user-images.githubusercontent.com/16945922/131738645-f3169a00-d7d9-43f3-95e6-cdf89fdf8191.png)

![image](https://user-images.githubusercontent.com/16945922/131738808-acce3876-52c1-4b25-be92-a3abf9dfe354.png)

GLPI version 9.5.5
Formscreator version v2.10.3

**Comment by btry** [comment]
Hi, 

this is a known problem, already fixed. Please apply this patch : https://github.com/pluginsGLPI/formcreator/commit/6d4c3af65e1c1ed336e1d35befff5ae9b321eea0

**Comment by luizfss** [comment]
Thank's! 

Its works!

**Comment by enumanc** [comment]
Hello, the issue seems to be still present but in another context.
When the form send a specific type equal to Request, in the associated ITIL category that should trigger a Ticket Template, the 'Request' type is not working, only the 'Incident' type trigger  a template. In global config the type configured is 'Incident'

**Comment by btry** [comment]
Hi

Can you open a new issue with a procedure to reproduce ? Don't forget to tell that you have the patch which solves this issue.
