### ISSUE TITLE
In 2.12.2, preview tab does not honor display conditions

### ISSUE THREAD

**Issue by nsalguero** [pluginsGLPI/formcreator#2409]
Hi,

With version 2.12.2, when I set a question be to displayed (or masked) only if a condition is met, in the preview tab, I see that that question is displayed regardless the condition applies or not (as if the javascript code responsible to hide the question was not played).
The problem only appears in the preview tab because, when the form is really used by someone, the display of that question respects the condition.

Best regards,

Nicolas Salguero.

**Comment by nsalguero** [comment]
I forgot to say that the same problem appears with the "Send" button.

**Comment by nsalguero** [comment]
Hi,

I finally understood the real problem: my forms can only be accessed by one profile.  If I add the "Super-Admin" profile, the issue is over.

Best regards,

Nicolas Salguero.

**Comment by btry** [comment]
Hi

This issue might be cause by rights check added recently : https://github.com/pluginsGLPI/formcreator/commit/ef3fc6623cfb2b9a1ebc7d6889179d895f2a0852

You form was not accessible from super-admin, then the rights check will the conditions evaluation. I must enhance the aboce code.

As you found a workaround, I'll postpone a bit the fix; because I'm busy elsewhere.

**Comment by nsalguero** [comment]
Hi,

I found that my workaround only works for active forms.  With an inactive form, the issue is still there.

Best regards,

Nicolas Salguero.

**Comment by btry** [comment]
Hi

Try this following fix, and feedback

#2413

**Comment by nsalguero** [comment]
Hi,

The fix solves the issue.

Many thanks!

**Comment by btry** [comment]
Thank you, the fix is merged.
