### ISSUE TITLE
Can't install FC 2.11.2 on GLPI 9.4.6

### ISSUE THREAD

**Issue by kintaro1981** [pluginsGLPI/formcreator#2472]
**Describe the bug**
Can't install FC 2.11.2 on GLPI 9.4.6

**To Reproduce**
1. Expland the plugin in the plugin directory
2. Reload plugin page
3. FC is not listed and a little banner say that the version support only GLPI 9.5

**Expected behavior**
AFAIK 2.11.2 is the last FC version supporting GLPI 9.4.x.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/2357176/143453817-4574d4d0-c2a0-4c0c-85f5-0d4decb8917f.png)

**GLPI / Plugins (please complete the following information):**
- GLPI version 9.4.6
- datainjection        Name: Data injection                 Version: 2.7.1      State: Enabled
- fusioninventory      Name: FusionInventory                Version: 9.4+2.5    State: Enabled
- mreporting           Name: More Reporting                 Version: 1.6.1      State: Enabled

**Comment by btry** [comment]
From what I see it seems this is not an error. the files plugin.xml and setup.php are consistent with GLPI version boundaries.

Re-reading the commit containing this lower boundary, I see there was a lot of code cleanup. This clearly intentional, as said in the commit message introducing this change.

There was a need to do some cleanup to make maintenance easier. I agree this should be avoided with a minor version, but keeping back compatibility created overhead at this time. I do my best to follow better rules, this case is exceptional and should not happen again un the near future.

I would recommend you upgrade to the latest GLPI and Formcreator because 2.11 is no longer maintained.

**Comment by kintaro1981** [comment]
ok I understand
The problem is that we use Slackware and until is released v.15 we are stuck in php5.6 :-(

Meantime I will try a previous version so I can study it 🧑‍🎓
