### ISSUE TITLE
Character limit in question titles

### ISSUE THREAD

**Issue by felipepimentel08** [pluginsGLPI/formcreator#2523]
If possible, double the character limit for the title of a text-type question.

**Comment by btry** [comment]
Hi

What is the maximum size you observed ?

**Comment by felipepimentel08** [comment]
256

**Comment by btry** [comment]
OK, this is what I expected. A title should be short. Maybe your title is long because it contains instructions to fill the answer. Is it possible for you to move some text to the description of the question or in a a question of type description (this type does not provides any input and is intended to show long rich text).

**Comment by felipepimentel08** [comment]
I see, I have this need, it's a long question of a form for LGPD (GDPR), below would have the options for him to select.

Only 3 questions were cut, is it possible to adjust in some file to increase the limit to 500 characters for example?

**Comment by btry** [comment]
HI

I prefer to avoid changing the title length because 255 characters shall be enough, and there are 2 possible alternatives, as I described.

Here is an example of the 2 alternatives; They should solve your concern. Also take note that you can use rich text.

![image](https://user-images.githubusercontent.com/14139801/147809881-c48499e5-ec46-48bb-b0a0-d429c6abcd82.png)

**Comment by felipepimentel08** [comment]
The text is in Pt-BR, see question 25 and 33, it was incomplete, I thought that way you showed it, but it was not good.
It would break out of the pattern of the form.

Is it possible then to inform me in which file I can change to increase the limit only on my server to meet this specific need?

![image](https://user-images.githubusercontent.com/47112555/147823418-c3480544-5c68-4847-b43f-99aea00c2ef8.png)

Below in English

![image](https://user-images.githubusercontent.com/47112555/147823544-71d3618c-6121-4ae2-9d0a-8214e371ec89.png)

**Comment by btry** [comment]
Changing the type of the column in the DB from VARCHAR to MEDIUMTEXT should be sufficient.

**Comment by felipepimentel08** [comment]
I changed the varchar itself from 255 to 500, it worked, thanks.
