### ISSUE TITLE
Form targets  UX

### ISSUE THREAD

**Issue by AdrienClairembault** [pluginsGLPI/formcreator#2606]
Two UX issues regarding form targets.
These issues come from the fact that targets are no longer in a modal but rather in a new dedicated page.

**1\) Can't open the target in new tab.**

If I click with the middle mouse button on the target nothing happen.

![image](https://user-images.githubusercontent.com/42734840/154495862-89aca93e-3baa-4717-a2ca-0f545e5cddf8.png)

This is because there is no actual link but rather an event watching for a right click : 

![image](https://user-images.githubusercontent.com/42734840/154496128-edaec0d9-6610-4cf2-aec6-3eea44ab5853.png)

We should either:
- Use an actual link
- Watch for others events that indicate that the user want to open the link in another browser tab (middle mouse button or CTRL + right click).

**2\) No way to go back to my form after editing a target**

Once I'm viewing a target, I have no button to go back to my form:

![image](https://user-images.githubusercontent.com/42734840/154496507-14af72bf-d9e2-43bc-a8e6-3692f698fd82.png)

Some other GLPI items implements a link to the current parent to avoid this issue, for example when viewing an antivirus you have a link to the parent computer:

![image](https://user-images.githubusercontent.com/42734840/154497096-44fb3b09-c9ce-4ffe-8999-d39594ff2499.png)

**Comment by btry** [comment]
> 2) No way to go back to my form after editing a target

To go back to your form you have the small icon representing a list 

![image](https://user-images.githubusercontent.com/14139801/154498974-a4d44504-e542-4464-b459-816e15bad3c9.png)

**Comment by AdrienClairembault** [comment]
> To go back to your form you have the small icon representing a list

This icon leads to `plugins/formcreator/front/targetticket.php` which doesn't exist.

![image](https://user-images.githubusercontent.com/42734840/154499892-afbe7f59-190d-4743-8c4e-c5c2b44aa442.png)

Also, anywhere else on GLPI this icon lead back to the main search page.
It would be wrong to have a specific action for only one item as it isn't predictable for users.

**Comment by AdrienClairembault** [comment]
The file doesn't exist in the repository, you can check it yourself:  https://github.com/pluginsGLPI/formcreator/blob/develop/front/targetticket.php
If you have it in local then you probably forgot to commit it.

**Comment by btry** [comment]
I pushed a fix in the dev branch to fix the 404 error.

> anywhere else on GLPI this icon lead back to the main search page.
It would be wrong to have a specific action for only one item as it isn't predictable for users.

in previous versions, targets where displayed in a modal, but this is no longer convenient because of the size of this modal. There are too many settings in targets, and this requires to organize them in a page with tabs, without modal. As targets list should show in the context of a form, the regular browsing design does not fit well the needs. I think it would be not convenient to show all targets of all forms in a list. This would also require a new menu entry in the menu, and in my opinion it would break  a consistent UI.
