### ISSUE TITLE
Formcreator 2.13.4 and 2.13.0beta1 : search by location and request group

### ISSUE THREAD

**Issue by mirda123** [pluginsGLPI/formcreator#2810]
**Is your feature request related to a problem? Please describe.**
Hi,  in catalog form, the user can't search tickets by :
- groupe demandeur (requesting group ?)
- Location

**Describe the solution you'd like**
Would it be possible to add that research choice ? it would be very helpfull

**Describe alternatives you've considered**
No idea...

**Additional context**

![location](https://user-images.githubusercontent.com/78594318/170656751-6657ff33-3f4f-4a04-975f-1fb8fe2ca81e.jpg)

**Comment by btry** [comment]
Hi

This is not possible to search assistance requests by location because a form answer cannot be associated to a location. Adding location to form answers is not planned, this is very likely meaningless.

Assistance requests don't support requester group for now, this is the reason of the absence of this criteria in the search engine.
