### ISSUE TITLE
"QUESTION" How Make visible only requests created with the form

### ISSUE THREAD

**Issue by tomdas** [pluginsGLPI/formcreator#2970]
**Describe the bug**
I would like users to only see the tickets created with the form that isl is not access to tickets prior to the release of the Form Creator plugin.

**Screenshots**

**GLPI / Plugins (please complete the following information): PLugin 2.12.5
- GLPI version : 9.5.7
- list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
- news                 Name: Alertes                        Version: 1.9.1      State: Enabled
	behaviors            Name: Comportements                  Version: 2.6.0      State: Enabled
	datainjection        Name: Data Injection                 Version: 2.10.2     State: Enabled
	escalade             Name: Escalades                      Version: 2.7.2      State: Not installed
	formcreator          Name: Form Creator                   Version: 2.12.5     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+4.2    State: Enabled
	order                Name: Gestion des commandes          Version: 2.7.6      State: Enabled
	mod                  Name: GLPI Modifications             Version: 2.0.2      State: Enabled
	moreticket           Name: More ticket                    Version: 1.6.1      State: Enabled
	onetimesecret        Name: OneTimeSecret                  Version: 1.1.2      State: Installed / not activated
	mreporting           Name: Plus de rapports               Version: 1.7.4      State: Enabled
	dashboard            Name: Tableau de bord                Version: 1.0.2      State: Enabled

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11 
 - Browser [e.g. chrome, safari] chrome ; edge

**Comment by tomdas** [comment]
Hello brty , 

Thanks a lot for your reply. Sorry , i'm use google translate.

we were using GLPI for a long time before the Forms creator plugin was put into production but glpi was not open to users. Now that we give them access we don't want them to be able to see the old tickets created.

**Comment by btry** [comment]
Formcreator does not forbids access to tickets  created before it has been installed, and this would be a bad idea to implement this restriction because it would make harder use the plugin on an already long lived GLPI instance.

I assume that your users who shall not see old tickets are requesters, and that they use the service cacalog interface of the plugin. You may delete from the table glpi_plugin_formcreator_issues all rows with the column date_creation older than the installation date of Formcreator. Check that the "Sync Issues" automatic actions is disabled in GLPI and never run it from the command line interface.

**Comment by tomdas** [comment]
Hello,

thanks again for your quick feedback.
I understand how it works but I don't think I'm going to get into it. It was really in case the feature was present.

Thanks again for your feedback.

Have a good day
