### ISSUE TITLE
IP ADDRESS

### ISSUE THREAD

**Issue by kirilwapj** [pluginsGLPI/formcreator#3066]
What needs to be done in order for the function of determining the ip address to work when working through a reverse proxy?

Because the ticket writes the ip address of the proxy.

In phpinfo I see values like this:

REMOTE_ADDR 172.16.1.11 (reverse proxy)
HTTP_X_FORWARDED_FOR 10.90.0.84 (real ip)

**Comment by btry** [comment]
Hi

Formcreator uses a method provided by GLPI to get the IP address of the user. It does not supports **HTTP_X_FORWARDED_FOR**.

**Comment by btry** [comment]
After investigation, support for **HTTP_X_FORWARDED_FOR** has been removed from GLPI to find the IP adfdress of a client because this HTTP header is not reliable and is source of security issues. It is up to you (or your administrator) to setup the HTTP server  to ensure that your HTTP server properly sets the HTTP header **REMOTE_ADDR** when used with a reverse proxy.
