### ISSUE TITLE
Missing #2789 in formcreator 2.12.7

### ISSUE THREAD

**Issue by plburguet** [pluginsGLPI/formcreator#3101]
Hello,
I went for an upgrade of GLPI and also this plugins, while testing everything at the end I encountered back the problem already submitted and fixed in #2789 
The fix is no longer in the code.

**Comment by btry** [comment]
Hi

> The fix is no longer in the code

From what I see this fix has been merged in Formcreator 2.13.x then it is not backported to 2.12.7

Since the release of Formcreator 2.13.0, versions 2.12.x reached end of life. I released exceptionnally a version 2.12.7 to address compatibility problem with GLPI 9.5.10 and 9.5.11, despite I'm overloaded with work since a few months. All bugfixes done for Formcreator 2.13.0 or later are **not** backported to 2.12.7.

The patch is quite small then you may backport it yourself. If you cannot or don't want to, then consider to subscribe to a [GLPI Network](https://services.glpi-network.com/) offer. This supports our work and you'll get help to backport the patch. Of course you also access support for other issues you may encounteer with your GLPI instance.
