### ISSUE TITLE
Download de imagens via acompanhamento

### ISSUE THREAD

**Issue by Wegilla** [pluginsGLPI/formcreator#3274]
Olá.
Um usuário anexou uma imagem (.png) via acompanhamento, quando fiz o download a imagem veio com outro formato (ticket.form.html), não sei o motivo dessa conversão.
Quem puder ajudar agradeço.
Versões: GLPI 10 e Form Creator 2.13.5 

Hello.
A user attached an image (.png) via tracking, when I downloaded the image it came with another format (ticket.form.html), I don't know the reason for this conversion.
Anyone who can help thank you.
Versions: GLPI 10 and Form Creator 2.13.5

**Comment by btry** [comment]
Hi

I speak English and French. Can you append a rewrite of your request in one of those language ? Translating your text with a tool gives a too much ambiguous result. I cannot understand well enough your problem.

**Comment by btry** [comment]
The image you uploaded is usually PNG or jpg. When you brows in glpi or Formcreator to view the image, it's format is the same. ticket.form.html does not matches any possible URL in glpi because all endpoints end with .PHP 

Can you show screenshots of the UI when you're about to upload an image, then show a screenshot when you display the uploaded image. Both screenshots must show the URL of the pages. You may redact the hostname, if necessary.

**Comment by btry** [comment]
Hi

Having no feedback, I assume your problem is solved and I close.
