### ISSUE TITLE
Formulário do FormCreator 

### ISSUE THREAD

**Issue by petrickfreitas** [pluginsGLPI/formcreator#3420]
Boa tarde! Alguém poderia me auxiliar com a seguinte situação... Quando vou criar um novo chamado usando o formulário do FormCreator, lá adicionei a opção de urgência, quando seleciono uma, ele sempre abre o chamado com a prioridade Média. Alguém sabe como corrigir?

Versões utilizadas:
- GLPI 10.0.10
- FormCreator 2.13.8

### english translation

Good afternoon! Could anyone help me with the following situation... When I create a new ticket using the FormCreator form, I added the urgency option, when I select one, it always opens the ticket with Medium priority. Does anyone know how to fix it?

**Comment by petrickfreitas** [comment]
Bom dia! Obrigado pelo retorno, mas não funcionou. 

![Captura de tela 2023-11-24 085437](https://github.com/pluginsGLPI/formcreator/assets/139565547/d50eae78-589b-4bd5-991e-bf01999d37d7)

**Comment by btry** [comment]
In the dropdown on the right (Question) you did not have any question available. Do you have in the form a question of type "Request type" ? I did not filled it in my previous screenshot because I used a form which donest have any "request type" question., then maybe you missed this requirement.

I did a test when a form has a question "request type", and the dropdown shows it as expected.

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/535489ec-b71c-484c-ad27-b5e6e54b248e)


![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/4e721365-1e5a-4dc2-b020-861bdbd4773b)

**Comment by petrickfreitas** [comment]
Fiz conforme ensinado, porém sem sucesso. Ainda continua abrindo os chamados com prioridade "Média" mesmo setando algum outro específico. 
![Captura de tela 2023-11-24 094740](https://github.com/pluginsGLPI/formcreator/assets/139565547/a602fd5a-2f02-4800-809c-33af9c71432b)
![Captura de tela 2023-11-24 094251](https://github.com/pluginsGLPI/formcreator/assets/139565547/37606894-a03b-4c38-93f7-3bf236ff1896)

**Comment by btry** [comment]
Oh sorry,  I've misread your 1st message. I answers you to set the type of the ticket : request or incident). For urgency, the settings is very similar. You must have an urgency question and set it as source for urgency in the target ticket. 

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/65ac7a1a-491f-4def-9567-9754c90b3704)

It works properly : i filled "very high" urgency, here is the generated ticket below

![image](https://github.com/pluginsGLPI/formcreator/assets/14139801/ac8d584e-4a69-456f-a37f-21a9f933ea80)

**Comment by petrickfreitas** [comment]
Muito obrigado! Funcionou perfeitamente agora.

**Comment by btry** [comment]
Great, then I close this issue.
