### ISSUE TITLE
FAQ on helpdesk form

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/formcreator#449]
Hello

is it possible to add faq on helpdesk form ?

Thank you

**Comment by btry** [comment]
Hi

You need to link a some form categories to knowbase categories. Then the knowbase entries tagged as FAQ should  display depending on the category you're viewing in Form Creator. This works for the regular mode and  the service catalog.

**Comment by satyan01** [comment]
I am sorry I don't understand, I just want to know if it is possible to add a tab on helpdesk page form with FAQ

**Comment by satyan01** [comment]
could you check my request #1679 and # 1671 on glpi please, it is a big miss for users

**Comment by btry** [comment]
No, because the new service catalog of FormCreator already provides such feature. I think it is what you need, but without the tab tou talked about.

Let me show you how it works if you did not explored it yet. I believe this will fufill your need, despite there is no extra tab.

How it looks like in the service catalog : 
![image](https://cloud.githubusercontent.com/assets/14139801/22290785/2c772158-e303-11e6-9341-fc34e2549f25.png)

How it looks like in  the regular FormCreator UI (a redesign of the older one in 0.90-1.3.4 )
![image](https://cloud.githubusercontent.com/assets/14139801/22290970/23f40946-e304-11e6-9c0f-f1db1b589371.png)

Locate the 2 tiles : 
![image](https://cloud.githubusercontent.com/assets/14139801/22290799/36591ffa-e303-11e6-8d7c-6b3ed09443d8.png)

The second one is a form, a thing you already know.

The first one, with the question mark, is an entry of the knowbase : 
![image](https://cloud.githubusercontent.com/assets/14139801/22290820/5678385c-e303-11e6-9832-309c22ed12b1.png)

To display it in FormCreator, you need to flag it as a FAQ entry : 
![image](https://cloud.githubusercontent.com/assets/14139801/22290848/7185ee8c-e303-11e6-87a7-ec2fe6c3a791.png)
and put it in a knowbase category (**General knowledge** in this example).

Next you need to link the category of the knowbase item to a category of forms

![image](https://cloud.githubusercontent.com/assets/14139801/22291001/4e53ebde-e304-11e6-9b91-dbed097ff730.png)

**Comment by satyan01** [comment]
Thank you for your help. However it would be easier for user to have directly access to faq in the menu .

**Comment by btry** [comment]
The purpose of this development is to promote the FAQ by an easier access. 

Some users may fill an assistance requests before searching in the FAQ. This generates useless requests if a FAQ entry exists and can provide an acceptable answer to the user. Moreover a solution in a FAQ entry provides a better service to the user as he can g et a solution to his problem immediately rather than waiting for a solution to a request.

With FormCreator 1.4.0 we hope users will find in a single manipulation both forms and FAQs, and select themselves a FAQ entry to get a faster answer if possible. This also would help to reduce the load on technicians.

Feel free to feedback with your experience.

**Comment by satyan01** [comment]
I understand your point of you, however, we are using faq for users for guidelines more than assistance.

Example : how to set up your remote connection at home, how to install your token on your blackberry...

So, when user asks to have this information, we redirect them or send the link to the faq.
