### ISSUE TITLE
Browser compatibility with new interface design

### ISSUE THREAD

**Issue by etiquet** [pluginsGLPI/formcreator#476]
Dear Community,

It seems with version 2.4 the UI have been vastly redesigned. 
When upgrading from a previous version, database needs update that generate a vast amount of error.
The UI is not compatible with Safari and various other browsers (IE8)
Currently this version won't fly in our production environment with our user current habits... 
Any option considered to offer a compatibility option with previous UI ?

Any help appreciated. 
With kind regards,
Eric

I joined a few screen capture to illustrate my request.

** the white background is not well adjusted

![capture d ecran 2017-02-04 a 18 12 30](https://cloud.githubusercontent.com/assets/18629332/22620269/69f86de0-eb08-11e6-8a88-7241c7da22fb.png)

** No forms are displayed

![capture d ecran 2017-02-04 a 18 10 27](https://cloud.githubusercontent.com/assets/18629332/22620270/70470698-eb08-11e6-8e0b-9e5fe925ab6b.png)

** Messy is nt it ?

![capture d ecran 2017-02-04 a 18 47 11](https://cloud.githubusercontent.com/assets/18629332/22620349/6a1f1a60-eb0a-11e6-8f1f-dce5d62eba9b.png)

**Comment by btry** [comment]
Hi

There are often browser cache issues. The last screenshot seems similari to other reports of messy display after an upgrade. Then I would advice you to hit CTRL+R or CTRL+F5 despite I guess you probalby already tried it.

This advice is in the readme because GLPI does not manage caching issues yet (this is incoming).

Once you removed caching issues, please report the remaining problems telling the operating system version and browser version for each CSS issue.

**Comment by etiquet** [comment]
Hi, this is the same view from different browsers. Did try the cache tips unfortunately, did not solve the issue.  Any option we could put a preference flag somewhere to activate "old style" / "new style" for compatibility issue ? This does not work at all with Safari and old browser. Eric

**Comment by orthagh** [comment]
Hello @etiquet 

I understand your issue but:
- Internet explorer 8 is not support by microsoft since 1 year
- Safari for windows (mac version should work by the way) isn't updated since 2012 and will never will be

The lib we are using (masonry) need minimum internet explorer 10 (released in 2010).

On GLPI project, we drop also the support for theses browsers and you will encounters more and more errors on the next versions.
IE10 is very minimum requirement nowadays.
