### ISSUE TITLE
"Add a destination" hangs & answers not loading

### ISSUE THREAD

**Issue by gohilurvish** [pluginsGLPI/formcreator#628]
formcreator v2.5.0
glpi v9.1.3

**Steps to reproduce "Add a destination" hang:**
1. Created a form
2. Press "add a destination"
3. Input Name and select type (tried with ticket and change)
4. Press "Add"
Screen goes blank and nothing comes on screen.
URL changes to "http://localhost/plugins/formcreator/front/target.form.php"

**Steps to reproduce "Answer not loading":**
1. Create a form "my_form"
2. Click on Preview or Targets->Link to the form or Assistance->Forms->my_form
3. Enter details
4. In the form, click "Form Answers"
Stuck at "Loading..."

Can anyone please help with this?

Thanks,

**Comment by btry** [comment]
I did a mistake with this release. I coded with PHP 5.6 in mind; but GLPI 9.1 is compatible with PHP 5.4. I began a compatibility fix. See #620 and #627

**Comment by btry** [comment]
Please tell the version of PHP you're using.

**Comment by gohilurvish** [comment]
PHP 5.4.17.

I just checked that data is there in a table "glpi_plugin_formcreator_answers".
But it is not able to show it.

**Comment by btry** [comment]
You need to apply patched version of inc/targetchange.class.php,  inc/targetticket.class.php and inc/form_answer.class.php

This will fix the identified compatibility issues in the code, and you will access your data.

**Comment by gohilurvish** [comment]
I just saw that in #620. I will try that out.
Sorry for duplicate. As I cannot understand the language, I created new issue.

**Comment by btry** [comment]
No problem.

The fix is maintained in this branch 

https://github.com/btry/formcreator/tree/feature/php_5_4_compatibility

There are 3 files tu pudate, as I described in french discussions.

https://raw.githubusercontent.com/btry/formcreator/feature/php_5_4_compatibility/inc/targetchange.class.php

https://raw.githubusercontent.com/btry/formcreator/feature/php_5_4_compatibility/inc/targetticket.class.php

https://raw.githubusercontent.com/btry/formcreator/feature/php_5_4_compatibility/inc/form_answer.class.php

**Comment by gohilurvish** [comment]
Thank You btry.
It works awesome now.

Your help was quick and to the point.
Thanks again.

**Comment by btry** [comment]
merged in 2.5.1
