### ISSUE TITLE
id in destination instead of login

### ISSUE THREAD

**Issue by Pieurre** [pluginsGLPI/formcreator#670]

**Comment by btry** [comment]
The following patch will be added in the next release.

https://github.com/pluginsGLPI/formcreator/pull/643/commits/75cd0347b35d1a8ba4ca0b2b14463e97e04422aa

which changes the behavior. Instead if the ID the destination contains firstname and realname of the user.

Now we need some specific trick to show the login instead of the firstname + realname. 

I also think we need some switch because some will need name other will need login.

**Comment by msizec** [comment]
hello,

did this patch is in the last release (2.5.2) as announced ?

Thx

**Comment by btry** [comment]
Hi

Yes, and I did not closed this ticket :(

I'll keep  it open until you confirm it works for you too

**Comment by btry** [comment]
This issue should be solved. Closing.
