### ISSUE TITLE
Business rules doesn't work on tickets from formcreator

### ISSUE THREAD

**Issue by msizec** [pluginsGLPI/formcreator#678]
We have business rules to set location of the ticket.
It seems these rules are not triggered when a ticket is created from a form validation.

Is it by design or I am missing something ?

Thx

**Comment by btry** [comment]
Hi

Please tell which version of GLPI and which version of FormCreatore you're using.

**Comment by btry** [comment]
Hi

I'm trying a simple setup with GLPI 9.1.6 and the development version of FormCreator. The rule which sets a location applies correctly.

Please show the rule to let me setup the same and see if it still works.

**Comment by btry** [comment]
Hi

Do you have any feedback about your issue ?

**Comment by btry** [comment]
probable duplicate or relation with #288

**Comment by btry** [comment]
Hi

I think I found  the issue. The problem seems to occur when rich text is enabled and the tested text contains accented characters. see #694. Remove accented characters from your rules, adapt the generated tickets to not contain accented characters i nthe parts you want to test. 

Also not that in version 2.6.0 the problem seems already solved.

Please feedback.

**Comment by btry** [comment]
Hi 

No feedback; then I close. If the issue still ocurs, please open a new ticket.

**Comment by btry** [comment]
Hi

I was informed  that #927 solves an issue with business rules on tickets. This PR is still in progress, and will be integrated in 2.6.3
