### ISSUE TITLE
Set self as answer

### ISSUE THREAD

**Issue by grvy** [pluginsGLPI/formcreator#793]
Is it possible for the plugin to set yourself (as in the person who is filling out the form) as the answer to a question?

**Comment by btry** [comment]
Hi

No, this is not implémented. You may workaround by creating a question to select a user, then use his answer to populate requesters. This requires a user input, so this is not the best for you.

From a technical point of view this is possible, but this need seems strange to me. What do you want to do with the answer ? Display it in a generated ticket or change ?

**Comment by grvy** [comment]
@btry we have one generic form which is basically "Open new ticket" and we have a question asking who it is that is requesting this. As we need that to populate the requester field?

**Comment by grvy** [comment]
Now that I actually think about it, the form is always submitted by the logged in user right? so this question on the form as in "who is requestin this" which I kinda just copied from the default new ticket from in GLPI isnt needed. As the system already knows this? is this thinking correct?

**Comment by btry** [comment]
Hi

The form is submitted by the user currently logged in, except if you use a form anonymously (accessible without being logged in).

The plugin gathers data from the fields, the current user's data and builds tickets or changes. 

As far as I understand, you're want the user filling the form to be a requester if the ticket it will generate. To do this, you got nothig to do. Add a atarget ticket to the form and see its default settings:

![image](https://user-images.githubusercontent.com/14139801/31582903-84d562b8-b190-11e7-92b6-d64be3d45cbc.png)

This is sufficient to have the user filling the form added as a requester of the generated ticket. For other forms you may want different settngs. For example, someone fills a form for someone else (because he lost his credentials ?). In such case, you can add a question to choose a user, and use the answer to this question to fill the requesters.

![image](https://user-images.githubusercontent.com/14139801/31582927-47b770d2-b191-11e7-8390-3ef70a36b178.png)

![image](https://user-images.githubusercontent.com/14139801/31582928-52f58ee8-b191-11e7-974a-1da285eef27a.png)

**Comment by grvy** [comment]
@btry yes, this works! I was being stupid, and didnt realize the form already knows. So I put a question to ask, but thats not needed. You can close this issue.
