### ISSUE TITLE
disappearing text if type field "description"

### ISSUE THREAD

**Issue by Geeskill** [pluginsGLPI/formcreator#813]
I see that when I use a "description" type field and then save it

if I reconsult it another time then its content disappears (unless the text has a specific format)

**Comment by btry** [comment]
Can you provide a screenshot, tell the version of GLPI and the version of the plugin ?

Also can you show me an example of text which does not disappears ? This mght reveal an escaping problem. Check glpi/files/_log/sql-errors.log and glpi/files/_log/php-errors.log for relevant errors and backtraces.

**Comment by Geeskill** [comment]
All the form : 

![formcreator1](https://user-images.githubusercontent.com/32699631/32099606-31e4d0cc-bb11-11e7-9174-61a101028e46.PNG)
![formcreator2](https://user-images.githubusercontent.com/32699631/32099608-36c87f44-bb11-11e7-9e6f-cf51a3a5f729.PNG)
![formcreator3](https://user-images.githubusercontent.com/32699631/32099611-3a1710ca-bb11-11e7-9f7a-55f7d77f4bc9.PNG)

The field description with text: 

![formcreator4](https://user-images.githubusercontent.com/32699631/32099638-5236ce34-bb11-11e7-937c-bb54cb56ccaf.PNG)
I save the question

after a while (variable) I find the form with this:

![formcreator5](https://user-images.githubusercontent.com/32699631/32099753-e541e3f8-bb11-11e7-8e77-dcc6884d7ced.PNG)

and I find my empty text field (while there is a protection to not save an empty field)

![formcreator6](https://user-images.githubusercontent.com/32699631/32099802-1a9ff54e-bb12-11e7-9cf4-0e0064aafc91.PNG)

I use GLPI 9.2 and FormCréator 2.6.0

**Comment by btry** [comment]
A huge form !

Something looks strange to me. Do you really need to wait for a while to observe the description being erased ? If you display your form quicker, the description displays as expected ?

**Comment by btry** [comment]
Hi

An issue found a few weeks ago may cause your issue. CAn you t ell me if the followiing scenario could match your form ?

- creation of a form **A** with a description question
- duplication of the form **A** into a copy **B**
- edit the description question in **B**
- observe the data is saved in **B**
- modify the description question in **A** (for example remove the text)
- observe the description question in **B** does no longer cotnains  the expected text.

The reason is the same description question instance is shared for both **A** and **B** due to a bug. It is fixed now, but if you duplicated a form when the bug was present, you have an inconsistency in your DB: a single isntance of a question shared between 2 forms. Therefore modifying the instance if a form will affect all other forms having a duplication relationship.

**Comment by btry** [comment]
Hi,

No feedback for several months, closing. If the issue persists, please open a new one.
