### ISSUE TITLE
Form status and closing

### ISSUE THREAD

**Issue by harryrmc** [pluginsGLPI/formcreator#926]
Hi

I have setup form with multiple destionations. When form is submittet a form-ticket is created and a ticket is created for every destination. When all tickets are resolved and closed, the form-ticket is still in the list of form answers. What I have noticed is:
* Form-ticket has no status telling if related tickets are closed or not.
* The ticket manager (even as super-admin) can not see form-ticket details if the requester is someone else.
* There is no way to "close" a form-ticket.

**Comment by btry** [comment]
Hi

The object you call *form-ticket* is only a container for the answers of the questions of a form. I prefer to call this a *answers set*, because it is closer to its actual purpose.

Consider a form as an empty form and a answers set as a filled form. Once the form is filled and submitted, it is processed to create tickets and/or changes.

Therefore, there is no need to define a status on an answers set. Your first and third bullets are in my opinion not a problem.

If the ticket manager needs to view the data of the answers set, he only need to view the generated tickets and changes. Maybe your second bullet spots a enhancement need. Let's focus on this and describe a use case and how to reproduce.

**Comment by btry** [comment]
Hi

Any  feedback ? Does my answer help you ?
