### ISSUE TITLE
[2.6.2] Useless backslashs in ticket title

### ISSUE THREAD

**Issue by nqb** [pluginsGLPI/formcreator#951]
Hello,

At @btry's request in #922, I open this issue. 

When you use characters like `"`or `'` as answer in a form and use this answer as ticket title, you have useless backslashs in ticket title : 
![useless_backslashs](https://user-images.githubusercontent.com/10830260/37970840-c5aa513a-31d4-11e8-9173-28adc455bb94.png)

Steps to reproduce : 
1. Create a form "Test" with a section and a question (type = text)
2. Define a destination called "MyDestination" (type=ticket)
3. Set "Ticket title" to `##answer_X##` with X, ID of your **answer**
4. Save your form
5. Fill you form
   * Answer to your question with  "Router doesn't work"
    * Send form

**Comment by btry** [comment]
Hi

Can you test the above PR please ?

**Comment by btry** [comment]
Positive feedback from a user impacted by the issue.

**Comment by ASLLR** [comment]
Hi everyone,

i reproduce that issue in formcreator 2.6.5 with GLPI 9.3.3. I think is a regression.

This issue was solved and tested with formcreator 2.6.3 with GLPI 9.2.3

That's exactly the same thing, with this `'` and this `"`

![capture](https://user-images.githubusercontent.com/37147055/50640866-6e1d3700-0f66-11e9-8d5a-efcc4f169f0f.PNG)

**Comment by btry** [comment]
Hi

I'm aware about regressions introduced in 2.6.5. Unfortunately I failed to solve some rendering issue without breaking something else. This is due to a technical debt I was progressively removing since 2.5.x.

This technical debt was completely removed in the version 2.7.0 (still in progress), and results seems very good. Feel free to evaluate it (branch develop). A beta was released, and some bugfixes are already added (mostly in the upgrade process )
